import { tool } from "@opencode-ai/plugin"
import type { WorkflowCtx } from "../types/workflow.ts"
import type { WorkflowConfig } from "../types/workflow.ts"
import { loadConfig, saveConfig } from "../storage/config.ts"
import { allMeta } from "../meta/index.ts"

// ─── Constants ────────────────────────────────────────────────────────────────

export const SUPPORTED_LANGUAGES = ["en", "fr", "es", "de", "pt", "it", "ja", "zh"] as const

// ─── Init text builder ────────────────────────────────────────────────────────

export function buildInitText(config: WorkflowConfig): string {
  return [
    "# BMAD Workflow — Quick Reference",
    "",
    "## Recommended cycle",
    "",
    "```",
    "1. /workflow-setup         → set language (fr, en, es…)                    [once per project]",
    "   /workflow-conventions  → generate ai-artifacts/conventions.md           [once per project, edit freely]",
    "2. /workflow-epic          → define an epic (scope, goal, priority)         [once per epic]",
    "3. /workflow-story         → create a BMAD story for that epic              [repeat per story]",
    "4. /workflow-status        → verify stories appear as ready-for-dev",
    "5. /workflow-sprint        → plan a sprint from your backlog                [once per sprint]",
    "6. /workflow-story-tasks   → list tasks in a story with index and status",
    "   /workflow-story-task   → implement one task at a time (safer, interruptible)",
    "   /workflow-story-dev    → implement all tasks in one shot (legacy, less control)",
    "   /workflow-task         → quick fix without epic/story (CSS, bug, tweak)  [shortcut]",
    "7. /workflow-story-update  → mark as review, then done                      [repeat per story]",
    "8. /workflow-review        → adversarial code review before closing          [optional]",
    "```",
    "",
    "## Story lifecycle",
    "",
    "```",
    "ready-for-dev → in-progress → review → done",
    "                                     ↘ superseded / deferred",
    "```",
    "",
    "## All tools",
    "",
    ...allMeta.map((m) => `- \`${m.name}\` — ${m.summary}`),
    "",
    "---",
    `Language: \`${config.language}\` — use \`workflow_setup\` to change.`,
    "Artifacts: `ai-artifacts/` — preview files in `ai-artifacts/.previews/` before every save.",
  ].join("\n")
}

// ─── Tool factories ───────────────────────────────────────────────────────────

export function createInitTool(ctx: WorkflowCtx) {
  return tool({
    description: "List available BMAD automated workflows. Use this as a starting point to pick a workflow or continue manually.",
    args: {},
    async execute() {
      const config = await loadConfig(ctx.directory)
      return buildInitText(config)
    },
  })
}

export function createSetupTool(ctx: WorkflowCtx) {
  return tool({
    description: "Configure workflow preferences for this project. Sets the language used for all generated documents.",
    args: {
      language: tool.schema
        .enum(SUPPORTED_LANGUAGES)
        .describe("Language code for generated documents. Supported: en, fr, es, de, pt, it, ja, zh."),
    },
    async execute(args) {
      await saveConfig(ctx.directory, args.language)
      return [
        `# Workflow setup saved`,
        ``,
        `Language set to \`${args.language}\`.`,
        `All documents generated by workflows will now be written in that language.`,
        ``,
        `Config saved to \`ai-artifacts/.workflow-config.json\`.`,
      ].join("\n")
    },
  })
}
