import type { OpencodeClient } from "@opencode-ai/sdk"
import { runAgentSession } from "../utils/session.ts"
import { writeDoc, timestamp } from "../utils/files.ts"
import { readdir, readFile } from "node:fs/promises"
import { join } from "node:path"

export interface EpicWorkflowOptions {
  client: OpencodeClient
  sessionId: string
  directory: string
  epicName: string
  epicGoal: string
}

export interface EpicsOverviewOptions {
  client: OpencodeClient
  sessionId: string
  directory: string
}

export async function runEpicWorkflow(opts: EpicWorkflowOptions): Promise<string> {
  const { client, sessionId, directory, epicName, epicGoal } = opts
  const ts = timestamp()
  const slug = epicName.toLowerCase().replace(/\s+/g, "-")
  const epicsDir = `.workflow/epics`
  const lines: string[] = []

  lines.push(`# Workflow: Epic — ${epicName}`)
  lines.push(`> Started at ${new Date().toISOString()}\n`)

  // ─── Step 1: PM → Epic definition ──────────────────────────────────────────
  lines.push("## Step 1/2 — PM: Defining epic scope...")
  const epicPrompt = `
Define a high-level epic using BMAD methodology.

Epic name: ${epicName}
Goal: ${epicGoal}

Include:
- Epic title and one-line description
- Business value and strategic goal
- List of features/stories that belong to this epic (high level, not detailed)
- Success metrics (how do we know the epic is done?)
- Dependencies on other epics
- Rough effort estimate (weeks/sprints)
- Priority (HIGH / MEDIUM / LOW)
`.trim()

  const epicDef = await runAgentSession(client, sessionId, directory, "pm", epicPrompt)
  const epicPath = await writeDoc(
    directory,
    `${epicsDir}/${slug}.md`,
    formatDoc("Epic", epicName, epicDef),
  )
  lines.push(`   ✓ Epic written → ${epicPath}`)

  // ─── Step 2: PM → Feature suggestions ──────────────────────────────────────
  lines.push("## Step 2/2 — PM: Suggesting features...")
  const featuresPrompt = `
Based on this epic, suggest the concrete features to implement.

${epicDef}

For each feature:
- Feature name (short, slug-friendly)
- One-line description
- User value
- Effort estimate (S/M/L)
- Priority within the epic

Format as a prioritized list ready to be used with workflow_feature.
`.trim()

  const features = await runAgentSession(client, sessionId, directory, "pm", featuresPrompt)
  const featuresPath = await writeDoc(
    directory,
    `${epicsDir}/${slug}-features.md`,
    formatDoc("Feature Suggestions", epicName, features),
  )
  lines.push(`   ✓ Features written → ${featuresPath}`)

  lines.push(`\n## Done ✓`)
  lines.push(`Generated docs in \`${epicsDir}/\`:`)
  lines.push(`  - ${slug}.md`)
  lines.push(`  - ${slug}-features.md`)
  lines.push(`\nUse \`workflow_feature\` to implement each feature, referencing epic: "${epicName}".`)

  return lines.join("\n")
}

export async function runEpicsOverview(opts: EpicsOverviewOptions): Promise<string> {
  const { client, sessionId, directory } = opts
  const epicsDir = join(directory, ".workflow/epics")
  const lines: string[] = []

  lines.push("# Epic Roadmap Overview")
  lines.push(`> Generated at ${new Date().toISOString()}\n`)

  // Read existing epic files
  let epicFiles: string[] = []
  try {
    const entries = await readdir(epicsDir)
    epicFiles = entries.filter((f) => f.endsWith(".md") && !f.includes("-features"))
  } catch {
    lines.push("No epics found yet in `.workflow/epics/`.\n")
    lines.push("Use `workflow_epic` to create your first epic.")
    return lines.join("\n")
  }

  if (epicFiles.length === 0) {
    lines.push("No epics found yet in `.workflow/epics/`.\n")
    lines.push("Use `workflow_epic` to create your first epic.")
    return lines.join("\n")
  }

  // Collect epic contents for the analyst
  const epicContents: string[] = []
  for (const file of epicFiles) {
    const content = await readFile(join(epicsDir, file), "utf-8")
    epicContents.push(`### ${file}\n\n${content}`)
  }

  // Ask analyst to produce a roadmap summary
  const analystPrompt = `
Produce a concise roadmap overview from these epic definitions.

${epicContents.join("\n\n---\n\n")}

For each epic:
- Name and one-line description
- Priority
- Rough effort
- Features listed
- Inferred status: TODO / IN PROGRESS / DONE (based on content clues)

Format as a prioritized table or list. End with a recommendation for which epic to tackle next.
`.trim()

  const overview = await runAgentSession(client, sessionId, directory, "analyst", analystPrompt)
  lines.push(overview)

  return lines.join("\n")
}

function formatDoc(type: string, name: string, content: string): string {
  return `# ${type}: ${name}\n\n> Generated by opencode workflow — ${new Date().toISOString()}\n\n---\n\n${content}\n`
}
