import type { OpencodeClient } from "@opencode-ai/sdk"
import { runAgentSession } from "../utils/session.ts"
import { writeDoc, timestamp } from "../utils/files.ts"

export interface FeatureWorkflowOptions {
  client: OpencodeClient
  sessionId: string
  directory: string
  featureName: string
  featureDescription: string
}

export async function runFeatureWorkflow(opts: FeatureWorkflowOptions): Promise<string> {
  const { client, sessionId, directory, featureName, featureDescription } = opts
  const ts = timestamp()
  const docsDir = `.workflow/${ts}-${featureName.toLowerCase().replace(/\s+/g, "-")}`
  const lines: string[] = []

  lines.push(`# Workflow: ${featureName}`)
  lines.push(`> Started at ${new Date().toISOString()}\n`)

  // ─── Step 1: PM → PRD ──────────────────────────────────────────────────────
  lines.push("## Step 1/3 — PM: Writing PRD...")
  const pmPrompt = `
Write a complete PRD for the following feature using BMAD methodology.

Feature: ${featureName}
Description: ${featureDescription}

Include:
- Overview & goals
- User stories (As a / I want / So that)
- Acceptance criteria (Given/When/Then)
- Out of scope
- Technical notes
`.trim()

  const prd = await runAgentSession(client, sessionId, directory, "pm", pmPrompt)
  const prdPath = await writeDoc(directory, `${docsDir}/PRD.md`, formatDoc("PRD", featureName, prd))
  lines.push(`   ✓ PRD written → ${prdPath}`)

  // ─── Step 2: Architect → Architecture ──────────────────────────────────────
  lines.push("## Step 2/3 — Architect: Designing architecture...")
  const archPrompt = `
Based on this PRD, design the technical architecture.

${prd}

Produce:
- Component overview
- Data flow
- Key technical decisions & tradeoffs
- File/module structure suggestion
- Risks & mitigations
`.trim()

  const arch = await runAgentSession(client, sessionId, directory, "architect", archPrompt)
  const archPath = await writeDoc(directory, `${docsDir}/ARCHITECTURE.md`, formatDoc("Architecture", featureName, arch))
  lines.push(`   ✓ Architecture written → ${archPath}`)

  // ─── Step 3: PM → Task list ─────────────────────────────────────────────────
  lines.push("## Step 3/3 — PM: Breaking down tasks...")
  const tasksPrompt = `
Based on this PRD and architecture, create a detailed task breakdown.

PRD:
${prd}

Architecture:
${arch}

Format as a numbered task list with:
- Task title
- Description (2-3 lines)
- Estimated effort (S/M/L)
- Dependencies (if any)
- Best suited agent (frontend / architect / reviewer / analyst)
`.trim()

  const tasks = await runAgentSession(client, sessionId, directory, "pm", tasksPrompt)
  const tasksPath = await writeDoc(directory, `${docsDir}/TASKS.md`, formatDoc("Task Breakdown", featureName, tasks))
  lines.push(`   ✓ Tasks written → ${tasksPath}`)

  // ─── Summary ────────────────────────────────────────────────────────────────
  lines.push(`\n## Done ✓`)
  lines.push(`Generated docs in \`${docsDir}/\`:`)
  lines.push(`  - PRD.md`)
  lines.push(`  - ARCHITECTURE.md`)
  lines.push(`  - TASKS.md`)
  lines.push(`\nYou can now continue manually or run \`workflow_review\` after implementation.`)

  return lines.join("\n")
}

function formatDoc(type: string, feature: string, content: string): string {
  return `# ${type}: ${feature}\n\n> Generated by opencode workflow — ${new Date().toISOString()}\n\n---\n\n${content}\n`
}
