import type { OpencodeClient } from "@opencode-ai/sdk"
import { runAgentSession } from "../utils/session.ts"
import { writeDoc, timestamp } from "../utils/files.ts"

export interface SprintWorkflowOptions {
  client: OpencodeClient
  sessionId: string
  directory: string
  sprintGoal: string
  durationWeeks?: number
}

export async function runSprintWorkflow(opts: SprintWorkflowOptions): Promise<string> {
  const { client, sessionId, directory, sprintGoal, durationWeeks = 2 } = opts
  const ts = timestamp()
  const docsDir = `.workflow/sprint-${ts}`
  const lines: string[] = []

  lines.push(`# Workflow: Sprint Planning`)
  lines.push(`> Started at ${new Date().toISOString()}\n`)

  // ─── Step 1: PM → Sprint plan ───────────────────────────────────────────────
  lines.push("## Step 1/2 — PM: Planning sprint...")
  const planPrompt = `
Create a sprint plan using BMAD methodology.

Sprint goal: ${sprintGoal}
Duration: ${durationWeeks} week(s)

Include:
- Sprint goal statement
- Prioritized user stories for this sprint (in scope)
- Stories explicitly out of scope (backlog)
- Definition of Done
- Risks and blockers
`.trim()

  const plan = await runAgentSession(client, sessionId, directory, "pm", planPrompt)
  const planPath = await writeDoc(directory, `${docsDir}/SPRINT-PLAN.md`, formatDoc("Sprint Plan", sprintGoal, plan))
  lines.push(`   ✓ Sprint plan written → ${planPath}`)

  // ─── Step 2: PM → Stories detail ───────────────────────────────────────────
  lines.push("## Step 2/2 — PM: Writing detailed stories...")
  const storiesPrompt = `
For each story in this sprint plan, write the full BMAD user story with acceptance criteria.

Sprint plan:
${plan}

For each story:
- Full user story (As a / I want / So that)
- Detailed acceptance criteria (Given/When/Then)
- Technical notes for developers
- Effort estimate (S/M/L)
`.trim()

  const stories = await runAgentSession(client, sessionId, directory, "pm", storiesPrompt)
  const storiesPath = await writeDoc(directory, `${docsDir}/STORIES.md`, formatDoc("User Stories", sprintGoal, stories))
  lines.push(`   ✓ Stories written → ${storiesPath}`)

  lines.push(`\n## Done ✓`)
  lines.push(`Generated docs in \`${docsDir}/\`:`)
  lines.push(`  - SPRINT-PLAN.md`)
  lines.push(`  - STORIES.md`)

  return lines.join("\n")
}

function formatDoc(type: string, goal: string, content: string): string {
  return `# ${type}\n> Goal: ${goal}\n> Generated by opencode workflow — ${new Date().toISOString()}\n\n---\n\n${content}\n`
}
