import { tool } from "@opencode-ai/plugin"
import type { OpencodeClient } from "@opencode-ai/sdk"
import { createStatusTool, createEpicPreviewTool, createEpicSaveTool, meta as epicMeta, metaStatus } from "./workflows/epic.ts"
import { createStoryPreviewTool, createStorySaveTool, meta as storyMeta } from "./workflows/story.ts"
import { createStoryUpdateTool, meta as storyUpdateMeta } from "./workflows/story-update.ts"
import { createStoryDevTool, meta as storyDevMeta } from "./workflows/story-dev.ts"
import { createSprintPreviewTool, createSprintSaveTool, meta as sprintMeta } from "./workflows/sprint.ts"
import { createReviewPreviewTool, createReviewSaveTool, meta as reviewMeta } from "./workflows/review.ts"
import { loadConfig, saveConfig } from "./utils/config.ts"
import type { WorkflowConfig } from "./types/workflow.ts"

type PluginCtx = {
  client: OpencodeClient
  directory: string
  worktree: string
  project: { root: string }
}

const allMeta = [metaStatus, epicMeta, storyMeta, storyUpdateMeta, storyDevMeta, sprintMeta, reviewMeta]

const SUPPORTED_LANGUAGES = ["en", "fr", "es", "de", "pt", "it", "ja", "zh"] as const

function buildInitText(config: WorkflowConfig): string {
  return [
    "# BMAD Workflow — Quick Reference",
    "",
    "## Recommended cycle",
    "",
    "```",
    "1. /workflow-setup         → set language (fr, en, es…)                    [once per project]",
    "2. /workflow-epic          → define an epic (scope, goal, priority)         [once per epic]",
    "3. /workflow-story         → create a BMAD story for that epic              [repeat per story]",
    "4. /workflow-status        → verify stories appear as ready-for-dev",
    "5. /workflow-sprint        → plan a sprint from your backlog                [once per sprint]",
    "6. /workflow-story-dev     → dev agent implements the story                 [repeat per story]",
    "7. /workflow-story-update  → mark as review, then done                      [repeat per story]",
    "8. /workflow-review        → adversarial code review before closing          [optional]",
    "```",
    "",
    "## Story lifecycle",
    "",
    "```",
    "ready-for-dev → in-progress → review → done",
    "                                     ↘ superseded / deferred",
    "```",
    "",
    "## All tools",
    "",
    ...allMeta.map((m) => `- \`${m.name}\` — ${m.summary}`),
    "",
    "---",
    `Language: \`${config.language}\` — use \`workflow_setup\` to change.`,
    "Artifacts: `ai-artifacts/` — preview files in `ai-artifacts/.previews/` before every save.",
  ].join("\n")
}

async function WorkflowPlugin(ctx: PluginCtx) {
  const { client, directory } = ctx
  const wfCtx = { client, directory }

  return {
    tool: {
      workflow_init: tool({
        description: "List available BMAD automated workflows. Use this as a starting point to pick a workflow or continue manually.",
        args: {},
        async execute() {
          const config = await loadConfig(directory)
          return buildInitText(config)
        },
      }),
      workflow_setup: tool({
        description: "Configure workflow preferences for this project. Sets the language used for all generated documents.",
        args: {
          language: tool.schema
            .enum(SUPPORTED_LANGUAGES)
            .describe("Language code for generated documents. Supported: en, fr, es, de, pt, it, ja, zh."),
        },
        async execute(args) {
          await saveConfig(directory, args.language)
          return [
            `# Workflow setup saved`,
            ``,
            `Language set to \`${args.language}\`.`,
            `All documents generated by workflows will now be written in that language.`,
            ``,
            `Config saved to \`ai-artifacts/.workflow-config.json\`.`,
          ].join("\n")
        },
      }),
      workflow_status: createStatusTool(wfCtx),
      workflow_epic_preview: createEpicPreviewTool(wfCtx),
      workflow_epic_save: createEpicSaveTool(wfCtx),
      workflow_story_preview: createStoryPreviewTool(wfCtx),
      workflow_story_save: createStorySaveTool(wfCtx),
      workflow_story_update: createStoryUpdateTool(wfCtx),
      workflow_story_dev: createStoryDevTool(wfCtx),
      workflow_sprint_preview: createSprintPreviewTool(wfCtx),
      workflow_sprint_save: createSprintSaveTool(wfCtx),
      workflow_review_preview: createReviewPreviewTool(wfCtx),
      workflow_review_save: createReviewSaveTool(wfCtx),
    },
  }
}

export { WorkflowPlugin }
export default WorkflowPlugin
