import { tool } from "@opencode-ai/plugin"
import type { OpencodeClient } from "@opencode-ai/sdk"
import { createEpicsTool, createEpicTool, meta as epicMeta, metaOverview as epicsMetaOverview } from "./workflows/epic.ts"
import { createFeatureTool, meta as featureMeta } from "./workflows/feature.ts"
import { createSprintTool, meta as sprintMeta } from "./workflows/sprint.ts"
import { createReviewTool, meta as reviewMeta } from "./workflows/review.ts"
import { loadConfig, saveConfig } from "./utils/config.ts"
import type { WorkflowConfig } from "./types/workflow.ts"

type PluginCtx = {
  client: OpencodeClient
  directory: string
  worktree: string
  project: { root: string }
}

const allMeta = [epicsMetaOverview, epicMeta, featureMeta, sprintMeta, reviewMeta]

const SUPPORTED_LANGUAGES = ["en", "fr", "es", "de", "pt", "it", "ja", "zh"] as const

function buildInitText(config: WorkflowConfig): string {
  const lines = ["# Available workflows\n"]
  for (const m of allMeta) {
    lines.push(`## ${m.name} — ${m.summary}`)
    lines.push(`   Chain: ${m.chain}`)
    lines.push(`   Generates: ${m.generates}\n`)
  }
  lines.push("---")
  lines.push("All docs are saved in `ai-artifacts/` at the project root.")
  lines.push(`\nCurrent language: \`${config.language}\` — use \`workflow_setup\` to change it.`)
  lines.push("\nStart with `workflow_epics` to see your roadmap, or `workflow_epic` to create your first epic.")
  return lines.join("\n")
}

async function WorkflowPlugin(ctx: PluginCtx) {
  const { client, directory } = ctx
  const wfCtx = { client, directory }

  return {
    tool: {
      workflow_init: tool({
        description: "List available BMAD automated workflows. Use this as a starting point to pick a workflow or continue manually.",
        args: {},
        async execute() {
          const config = await loadConfig(directory)
          return buildInitText(config)
        },
      }),
      workflow_setup: tool({
        description: "Configure workflow preferences for this project. Sets the language used for all generated documents (epics, features, sprints, reviews).",
        args: {
          language: tool.schema
            .enum(SUPPORTED_LANGUAGES)
            .describe("Language code for generated documents. Supported: en, fr, es, de, pt, it, ja, zh."),
        },
        async execute(args) {
          await saveConfig(directory, args.language)
          return [
            `# Workflow setup saved`,
            ``,
            `Language set to \`${args.language}\`.`,
            `All documents generated by workflows will now be written in that language.`,
            ``,
            `Config saved to \`ai-artifacts/.workflow-config.json\`.`,
          ].join("\n")
        },
      }),
      workflow_epics: createEpicsTool(wfCtx),
      workflow_epic: createEpicTool(wfCtx),
      workflow_feature: createFeatureTool(wfCtx),
      workflow_sprint: createSprintTool(wfCtx),
      workflow_review: createReviewTool(wfCtx),
    },
  }
}

export { WorkflowPlugin }
export default WorkflowPlugin
